fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
      ref: "4.1.0"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    epel:
      repo: "https://github.com/voxpupuli/puppet-epel"
      ref: "v4.1.0"
