---
common:
  disable_legacy_facts: true

spec/spec_helper.rb:
  mock_with: ":rspec"
  default_facter_version: '3.6.9'
  coverage_report: true

Rakefile:
  github_user: mleiner

Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '~> 1.15'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.3.0')"

spec/default_facts.yml:
    extra_facts:
        'os':
          'family': 'Debian'
        'networking':
          'domain': 'localnet'

.gitlab-ci.yml:
  custom:
    use_litmus: false
    litmus:
      provision_list: [centos7, debian9, debian10, debian11, ubuntu1804, ubuntu2004]
      puppet_collection: [puppet6, puppet7]

.travis.yml:
  use_litmus: true
  branches:
    - master
    - /^v\d/
