notifications:
  email:
  - mleiner@noris.net
rvm:
- 2.4.5
- 2.5.3
env:
  matrix:
  - PUPPET_VERSION=5
  - PUPPET_VERSION=6
matrix:
  exclude:
  - rvm: 2.4.5
    env: PUPPET_VERSION=6
  - rvm: 2.5.3
    env: PUPPET_VERSION=5
